# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2b851786e39610c4120a32a0b5b09a920a0a147fa85724deb3af62da8649aef62079d5436326c4289067eca8162b49911ab55f8f2c4a083f86d7d2f1f06b2d5

test:
  secret_key_base: 62b3398977716bd38569f501e9a2164e97b0356efa4a7279e5cda7e705626485e883b9c81cc7056bf358120e62a0f4df8b661b83a170f1ee0687a7c3f292bd38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
